### ISSUE TITLE
AudioVideoPlayback does not compile

### ISSUE THREAD

**Issue by David-Sanders** [mistaguy/AudioVideoPlayBack#1]
The widget does not compile in Mendix 5.16.0 when creating a deployment package.  The following error is shown in the dojo/build-report.txt:

error(333) Missing dependency in legacy module.
    reference module: AudioVideoPlayback/AudioVideoPlaybackList; dependency: AudioVideoPlayback/SoundManager/soundmanager2

**Comment by acellam** [comment]
I have converted the whole project into AMD, I have removed every code that is not supposed to be part of the widget. However the current mainline is unstable. Your contribution will be appreciated

**Comment by acellam** [comment]
The app now compiles and there are not issues.
I am fixing playing music from a URL
