### ISSUE TITLE
build on 5.16.1+ fails

### ISSUE THREAD

**Issue by Achiel** [mistaguy/AudioVideoPlayBack#3]
Heya,

this widget doesn't seem to be building on 5.16.1+, due to jquery not being loaded correctly.

I'd suggest you remove the duplicate jquery versionsin your lib (you seem to have jquery.js and jquery-1.11.2.min.js) and replace them with the jquery from this pull request: 
https://github.com/mendix/AppStoreWidgetBoilerplate/pull/13

That version omits the string in the define on line 10307. 

If you change all dependencies to that jquery version you should be ok. AFAICT that's only jquery.jplayer.js

Let me know if there's anything else I can do to help :)
## 

Achiel

**Comment by mistaguy** [comment]
I have include your suggestion but i am running into this error

404 - file not found for file: mxclientsystem/jquery.js

**Comment by acellam** [comment]
I have used your suggestion but i am running into this error.

404 - file not found for file: mxclientsystem/jquery.js

**Comment by Achiel** [comment]
You also need to update jquery.jplayer.js to point to that jquery. You'll need to use a full path.

**Comment by acellam** [comment]
[v3.0.1 fixes has your suggests and fixes deployment issues.Click Link for details](https://github.com/mistaguy/AudioVideoPlayBack/releases/tag/v3.0.1)

**Comment by Achiel** [comment]
Thanks!
